### ISSUE TITLE
Where is the 30 second timer?

### ISSUE THREAD

**Issue by jelkner** [Quartezy/itd110#8]
I was sooo eager to look at your 30 second timer I jumped into this repo first, but alas, I can't find it.

Please commit that work and link to it under the Projects section of your homepage.  You could either make a subdirectory for this here, or even better, create a new repo entirely.

Please remind me to discuss that with the group on Tuesday.

**Comment by Hessonight** [comment]
It was in another repository, now there's a link for it on my homepage

**Comment by jelkner** [comment]
Putting it in another repository is a great idea.  And now that I found it (https://github.com/Quartezy/timer), I'll clone it and experiment with it over the weekend.  On Tuesday we can figure out a good place to host this project so we can collaborate on it.
